name: CD Deploy to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Backend Container
      uses: azure/aci-deploy@v1
      with:
        resource-group: YOUR_RG_NAME
        name: cloudmart-backend
        image: ${{ secrets.DOCKERHUB_USERNAME }}/cloudmart-backend:latest
        dns-name-label: cloudmart-backend-1902327
        ports: 8000
        environment-variables: |
          COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }}
          COSMOS_KEY=${{ secrets.COSMOS_KEY }}

    - name: Deploy Frontend Container
      uses: azure/aci-deploy@v1
      with:
        resource-group: YOUR_RG_NAME
        name: cloudmart-frontend
        image: ${{ secrets.DOCKERHUB_USERNAME }}/cloudmart-frontend:latest
        dns-name-label: cloudmart-frontend-1902327
        ports: 5173
        environment-variables: |
          VITE_API_URL=https://cloudmart-backend-1902327.canadacentral.azurecontainer.io
